# ===================================================
# KONFIGURASI FINAL UNTUK ZUHAYRGIM.GITHUB.IO
# ===================================================

title: ZuhayrGim
description: "Zuhayrgim provides free game mods, the latest updates, and safe direct download links for popular games."

# URL utama website Anda
url: "https://zuhayrgim.github.io"
baseurl: "" # WAJIB KOSONG untuk tipe repo ini

# --- Pengaturan URL Cantik ---
permalink: /:slug/

# --- Pengaturan Plugin ---
# Mendaftarkan plugin yang kita gunakan
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag 

# --- Pengaturan Pagination ---
paginate: 7
paginate_path: "/page/:num/"

# --- Pengaturan Postingan Populer ---
# Ganti dengan judul-judul artikel Anda yang sebenarnya
popular_posts:
  - "Free Download Mod Merge Fellas 1.8.9 – Unlimited Shakes, revives, hammer and No Ads"
  - "Plant VS Zombies: Free to Modify Again"
